version: 2
jobs:
  build:
    working_directory: /go/src/github.com/SpectoLabs/hoverfly
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test